### ISSUE TITLE
Enhancement for selecting editors

### ISSUE THREAD

**Issue by rtournoy** [CCSDForge/episciences#148]
Depending on journal settings, if the journal allows to select one or more editor, do not auto-select the first editor in the list.
Add a message to explain how to select multiple editors (e.g. CTRL + click)

- Source gitlab 369 + 392

**Comment by a3nm** [comment]
As a user, I agree the Ctrl+Click behavior is not very intuitive. From the advice at https://www.w3schools.com/tags/att_select_multiple.asp I wonder if it wouldn't be more user-friendly to use checkboxes. (For my journals, though, we don't have the setting in question toggled, so that's just my opinion!)

**Comment by rtournoy** [comment]
completed, we forgot to close the issue
