### ISSUE TITLE
LMCS: feature request - revision deadline

### ISSUE THREAD

**Issue by HeleneLowinger** [CCSDForge/episciences#227]
[https://gitlab.ccsd.cnrs.fr/ccsd/episciences/-/issues/361]

(Demande Stefan Milius https://support.ccsd.cnrs.fr/Ticket/Display.html?id=124657)
the following feature would be helpful for editors and chief editors:
On the administration page (possibly also in the table one page before that list assigned papers of an editor), revision deadlines should be display. (Possibly the revision deadline should be adjustable by editors.) This could be displayed in the 'Revision requests' box.
At the moment there is only the date of the last request and then the text of the email gives an indication of the deadline. But there is no way to know for sure what is the real deadline in the system.

**Comment by rtournoy** [comment]
Is it on /administratepaper/list ? or /user/dashboard ?

**Comment by smilius42** [comment]
I mainly mean the admin page of the submission (e.g. https://lmcs.episciences.org/administratepaper/view?id=9445). The revision deadline could be displayed as the first line of the 'Revision requests' box, e.g. 
Revised version expected: <data>

And this date should be adjustable by the editor (similar to reviewing deadlines being adjustable). 

In addition the 'revised version expected' date could be shown in the tables (e.g. https://lmcs.episciences.org/administratepaper/list)  that editor see when the click the links in their dashboard. There it could be shown onMouseOver of the colored squares in the 'Status' column. (Similar to review deadlines being shown onMouseOver in the 'Reviewers' column) A new extra column is perhaps less useful because already now not all columns are displayed; they are clipped and one needs to scroll to see the last two columns.

**Comment by rtournoy** [comment]
Fixed in release https://github.com/CCSDForge/episciences/releases/tag/v1.0.33
