### ISSUE TITLE
[Bug Report] %%RATING_DEADLINE%% not correctly substituted in outgoing emails / Le tag %%RATING_DEADLINE%% n'est pas substitué correctement dans les messages sortants

### ISSUE THREAD

**Issue by emperrin** [CCSDForge/episciences#273]
[https://support.ccsd.cnrs.fr/Ticket/Display.html?id=167820]

With Theoretics's workflow, we need to use some tags like "%%RATING_DEADLINE%%" in multiple places in the reviewer invitation email template. But it appears that these do not correctly get substituted. Specifically, it seems that when starting to compose the message the first occurrence of "%%RATING_DEADLINE%%" in the template is substituted, but any remaining occurrences of "%%RATING_DEADLINE%%" are silently removed (and not replaced) when sending the message.
Would it be possible to make sure that "%%RATING_DEADLINE%%" is correctly substituted in outgoing emails? and/or that all occurrences of "%%RATING_DEADLINE%%" (not just the first one) are substituted when starting to compose the message?

Dans le workflow de Theoretics, nous devons utiliser des balises telles que "%%RATING_DEADLINE%%" à plusieurs endroits dans le message d'invitation des évaluatueurs. Mais il semble que ces balises ne sont pas correctement substituées. Plus précisément, il semble que, lors de la composition du message, la première occurrence de "%%RATING_DEADLINE%%" est remplacée, mais que toutes les autres occurrences de "%%RATING_DEADLINE%%" sont supprimées (et non remplacées) lors de l'envoi du message.
Serait-il possible de faire en sorte que "%%RATING_DEADLINE%%" soit correctement remplacé dans les messages sortants ? et/ou que toutes les occurrences de "%%RATING_DEADLINE%%" (et pas seulement la première) soient remplacées au moment de commencer à composer le message ?

**Please do not disclose any personal information (e.g. name of an author, reviewer, email addresses, etc.).**

Please use the support address if you need to mention personal data

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser and Operating System (please complete the following information):**
 - OS: [e.g. iOS, Windows, GNU/Linux]
 - Browser [e.g. Chrome, Firefox, Safari]
 - Version [e.g. 42]

**Additional context**

**Comment by devletech** [comment]
Fixed: https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#fixed-1 (RT#167820)

**Comment by a3nm** [comment]
Thanks @devletech ! I agree that this fixes the immediate problem.

However, I realize that the behavior is strange. The tag "%%RATING_DEADLINE%%" is substituted when we start to compose the message. However, before sending the message, there is the option of changing the "Rating due date" in the form. Of course, if the editor changes the rating due date, then this is not reflected in the message (because the substitution has already happened).

Wouldn't it make more sense for the tag "%%RATING_DEADLINE%%" to be substituted not when composing the message, but when sending it? (substituting it with the "Rating due date" that was given by the user in the form)

Please let me know! and thanks for your efforts.

**Comment by devletech** [comment]
Fixed: https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#10342---2022-10-18
