### ISSUE TITLE
[Bug Report] Unable to upload a new resource file on the web site

### ISSUE THREAD

**Issue by vacary** [CCSDForge/episciences#282]
I am unable to upload a new resource file on the web site of JTCAM. When I select a file, the following directory appears 

```C:\fakepath\jtcam_episciences.zip```

that prevents to proceed further.

**Comment by a3nm** [comment]
Hi @vacary, not an Episciences dev but on our instance of Episciences it works despite the "fakepath" thing -- you can just then click on "Select the file" (the name of this button is a bit odd btw) and it works. Have you tried this?

**Comment by rtournoy** [comment]
Hi @vacary , It looks like a weird label added by browsers, used as a kind of privacy feature, to not display the full path  to the file. As @a3nm commented you should be able to continue. If it doesn't work please tell us on which form it fails we may have skipped a bug. @devletech has updated the code to hide this label, because it can be confusing
