### ISSUE TITLE
[Bug Report] TheoretiCS Header not displaying

### ISSUE THREAD

**Issue by davidjpurser** [CCSDForge/episciences#450]
**Describe the bug**

The Header, set inside Website > Header does not show up on the website. 
It works correctly on https://theoretics-preprod.episciences.org/

**To Reproduce**
Steps to reproduce the behaviour:

- See: https://theoretics.episciences.org/website/style There are header elements
- See: https://theoretics.episciences.org/ The header elements are not generated

The logo currently displaying on https://theoretics.episciences.org/ is due to a hack on the sidebar, not using the header features.

The HTML generated by preprod is correctly:
```
<div class="logo">
        <table width="100%" cellpadding="0" style="position:relative;">
<tr>
<td align="center"><a href="[/](view-source:https://theoretics-preprod.episciences.org/)" border="0" target="_blank"><img src="[https://theoretics-preprod.episciences.org/public/TheoretiCS_logo_light_red_1.svg](view-source:https://theoretics-preprod.episciences.org/public/TheoretiCS_logo_light_red_1.svg)" width="275px" alt="TheoretiCS-preprod" /></a></td>
<td align="left"><span class="warningsep"></span></td>
<td align="left"><span>An open access journal in theoretical computer science</span></td>
</tr>
</table>
    </div>
```

The HTML generated by production is incorrectly: 

```
    <div class="logo">
        <table width="100%" cellpadding="0" style="position:relative;">
<tr>
</tr>
</table>
    </div>
```

The table is built using createHeader() in https://github.com/CCSDForge/episciences/blob/main/library/Ccsd/Website/Header.php and saves it to a file, since the table and tr is built, either the `foreach ($this->_logos as $logo) {` is incorrectly returning empty (although it is correctly in the database, as the content can be seen at https://theoretics.episciences.org/website/style), or the save to file is broken so it is 'stuck' on an old version without being updated.

## Side Note 
It would be much better if the target for the image link could either be `_self` or choosable (but this is a new feature request not a bug) at the following point: https://github.com/CCSDForge/episciences/blob/afbfe2bc48ec4fd075784f085aef2805c467b33e/library/Ccsd/Website/Header.php#L284C71-L284C91

**Comment by rtournoy** [comment]
Thank you very much for the detailed bug report. I really makes a difference for the debug. 

The problem was that the file could not be written because of an ownership problem. We have fixed the issue, check the other files (OK), you should now be able to proceed. Additionally the target of the link of a logo is now `_self`. But you have to save the header again to see the difference - I have saved the header for https://theoretics-preprod.episciences.org/

The full change log for v1.0.42.3 is available here:
https://github.com/CCSDForge/episciences/blob/main/CHANGELOG.md#v10423---2024-03-20
