### ISSUE TITLE
Paper order within a volume is broken

### ISSUE THREAD

**Issue by t-wissmann** [CCSDForge/episciences#46]
It seems to happen that after some time, the order of the papers within a volume gets broken and moreover can't be fixed. Maybe there are a couple of related issues, maybe it's just one issue:

# Volume is messed up after some time
Concretely, in LMCS in [Volume 16, Issue 4](https://lmcs.episciences.org/volume/view/id/417), the papers ['psi-calculi' 16(4:16)](https://lmcs.episciences.org/6981) and ['ticking' 16(4:17)](https://lmcs.episciences.org/6980) are listed wrong order on the volume's page (as one can tell from the DOI on the article's page). I am very sure that the order was OK in January, because I have a script that I run locally and that verifies the order of articles within a volume. I run the script after every volume, and this is how I just discovered the wrong order in nearly all volumes that I've checked, some of them are evern really old (16/4, 17/1, 17/2, [16/2](https://lmcs.episciences.org/volume/view/id/401), [16/1](https://lmcs.episciences.org/volume/view/id/389) [13/1](https://lmcs.episciences.org/volume/view/id/299)), e.g. the first paper listed in [13/1](https://lmcs.episciences.org/volume/view/id/299) is https://doi.org/10.23638/LMCS-13(1:3)2017, which actually should be listed third.

# Changing order does not update the public volume page
In *Volume 16, Issue 4* I have fixed the order manually on [Edit this volume](https://lmcs.episciences.org/volume/edit?id=417) but the [volume browser](https://lmcs.episciences.org/volume/view/id/417) still shows the old/wrong order. How long does it take to be updated? For instance, I've changed the [order in 17/2](https://lmcs.episciences.org/volume/edit?id=437) today at 16:00 but the [volume browser](https://lmcs.episciences.org/volume/view/id/437) still shows the wrong order (at 18:30) (note how the first two papers are swapped)

**Comment by rtournoy** [comment]
The bug affected only the public display of the position of papers ; i.e. nothing was wrong with the data. We were sorting with an identifier that was no longer relevant for sorting papers inside the volumes.

For the context:
Each version of a paper has its own unique _docid_
Each version of a paper also has a unique _paperid_ common for all versions of the same paper

Example:
- docid 1   ; paperid 1
- docid 3   ; paperid 1 
- docid 31 ; paperid 1

Some time ago we started using _paperids_ to sort papers positions because it is consistent across all document versions, previously we were using _docids_ which are different for each version of a document.
But we forgot to update the way papers are sorted for public displays of volumes and were still using a _docid_.

Thank you very much for the clear report, and all apologies for the inconvenience. I can't reproduce the bug after the fix has been pushed online, but please comment or reopen if I forgot something.

**Comment by t-wissmann** [comment]
Thanks a lot for fixing the issue and for the explanations!
The order is correct now in all the volumes that I've checked ([13/1](https://lmcs.episciences.org/volume/view/id/299), [16/1](https://lmcs.episciences.org/volume/view/id/389), [16/4](https://lmcs.episciences.org/volume/view/id/417), [17/1](https://lmcs.episciences.org/volume/view/id/424), [17/2](https://lmcs.episciences.org/volume/view/id/437))
